# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78bde7f90c653eae13230651cfcbdc60a660d3351535485ad6f0889136525c653670c4bccbeb141a876a4aabf0ca0d29ea7fc854fe722cb2aaf868780bda950f

test:
  secret_key_base: 868c50ecb574db4a46089937de5be0805bbf91460034bd5b3181bca1e3e239c143ea1d16a20c826d188496813ccb994b1a247935407ea5975581e0d52550ba4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
